// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'appointment_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AppointmentData _$AppointmentDataFromJson(Map<String, dynamic> json) =>
    AppointmentData(
      json['startDate'] as String?,
      json['endDate'] as String?,
      json['marketSegment'] as String?,
      json['activityType'] as String?,
      json['assignedTo'] as String?,
      json['assignedToName'] as String?,
      json['assignedToEmail'] as String?,
      json['assignedToPhone'] as String?,
      json['name'] as String?,
      json['comments'] as String?,
      json['id'] as String?,
      json['projectId'] as String?,
      json['completed'] as String?,
      json['sendInstallerSMS'] as bool?,
      json['prospectName'] as String?,
      json['prospectPhoneNumber'] as String?,
      json['prospectFullAddress'] as String?,
      json['prospectAddress'] as String?,
      json['prospectCity'] as String?,
      json['prospectState'] as String?,
      json['prospectZipCode'] as String?,
      json['prospectPrimaryEmail'] as String?,
      json['projectCoordinator'] as String?,
      json['projectCoordinatorPhone'] as String?,
      json['projectCoordinatorId'] as String?,
      json['saleId'] as String?,
      json['saleNumber'] as String?,
      json['saleSummaryReportURL'] as String?,
      json['picklistReportURL'] as String?,
      json['laborBillReportURL'] as String?,
      json['installAfterPhotosURL'] as String?,
      json['installBeforePhotosURL'] as String?,
      json['isArrivalConfirmed'] as bool?,
      json['installerArrivalDateTime'],
      json['isInstallConfirmed'] as bool?,
      json['installerNotificationConfirmed'],
      json['errors'],
      json['message'],
      json['success'] as String?,
      json['installationManager'] as String?,
      json['installationManagerPhone'] as String?,
      json['installCoordinatorManager'] as String?,
      json['installCoordinatorManagerPhone'] as String?,
      json['appointmentLongitude'] as String?,
      json['appointmentLatitude'] as String?,
    );

Map<String, dynamic> _$AppointmentDataToJson(AppointmentData instance) =>
    <String, dynamic>{
      'startDate': instance.startDate,
      'endDate': instance.endDate,
      'marketSegment': instance.marketSegment,
      'activityType': instance.activityType,
      'assignedTo': instance.assignedTo,
      'assignedToName': instance.assignedToName,
      'assignedToEmail': instance.assignedToEmail,
      'assignedToPhone': instance.assignedToPhone,
      'name': instance.name,
      'comments': instance.comments,
      'id': instance.id,
      'projectId': instance.projectId,
      'completed': instance.completed,
      'sendInstallerSMS': instance.sendInstallerSMS,
      'prospectName': instance.prospectName,
      'prospectPhoneNumber': instance.prospectPhoneNumber,
      'prospectFullAddress': instance.prospectFullAddress,
      'prospectAddress': instance.prospectAddress,
      'prospectCity': instance.prospectCity,
      'prospectState': instance.prospectState,
      'prospectZipCode': instance.prospectZipCode,
      'prospectPrimaryEmail': instance.prospectPrimaryEmail,
      'projectCoordinator': instance.projectCoordinator,
      'projectCoordinatorPhone': instance.projectCoordinatorPhone,
      'projectCoordinatorId': instance.projectCoordinatorId,
      'saleId': instance.saleId,
      'saleNumber': instance.saleNumber,
      'saleSummaryReportURL': instance.saleSummaryReportURL,
      'picklistReportURL': instance.picklistReportURL,
      'laborBillReportURL': instance.laborBillReportURL,
      'installAfterPhotosURL': instance.installAfterPhotosURL,
      'installBeforePhotosURL': instance.installBeforePhotosURL,
      'isArrivalConfirmed': instance.isArrivalConfirmed,
      'installerArrivalDateTime': instance.installerArrivalDateTime,
      'isInstallConfirmed': instance.isInstallConfirmed,
      'installerNotificationConfirmed': instance.installerNotificationConfirmed,
      'errors': instance.errors,
      'message': instance.message,
      'success': instance.success,
      'installationManager': instance.installationManager,
      'installationManagerPhone': instance.installationManagerPhone,
      'installCoordinatorManager': instance.installCoordinatorManager,
      'appointmentLongitude': instance.appointmentLongitude,
      'appointmentLatitude': instance.appointmentLatitude,
      'installCoordinatorManagerPhone': instance.installCoordinatorManagerPhone,
    };
